image: golang:1.7

pipelines:
  default:
    - step:
        script:
          - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game &&  cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/no-name

          # Manage dependencies
          - cd /go/src/bitbucket.org/no-name-game/no-name
          - curl https://glide.sh/get | sh
          - ${GOPATH}/bin/glide install

          # Build and test
          - go build -v
