image: golang

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game
            - cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram

            # Clono SDK
            - git clone git@bitbucket.org:no-name-game/nn-grpc.git ${GOPATH}/src/bitbucket.org/no-name-game/nn-grpc

            # Linter checks
            - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
            - golangci-lint run

            # Build and test
            - cd ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram
            - go build -v