image: golang

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game &&  cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram

            # Update submodule NNSDK
            - git submodule update --init

            # Linter checks
            - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
            - golangci-lint run

            # Build and test
            - go build -v