image: golang

pipelines:
  default:
#    - step:
#        name: Test echo
#        script:
#          - echo "test echo"
#    - step:
#        name: Runner Setup
#        image: guglio/dind-buildx:latest
#        runs-on:
#          - self.hosted
#          - valkyrie
#        services:
#          - docker
#        script:
#          - echo "Executing on self-hosted runner"
#          - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; docker buildx create --use
#    - step:
#        name: Setup Project
#        runs-on:
#          - self.hosted
#          - valkyrie
#        services:
#          - docker
#        script:
#          - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game
#          - cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram
#          - git clone -b develop git@bitbucket.org:no-name-game/nn-grpc.git ${GOPATH}/src/bitbucket.org/no-name-game/nn-grpc
    - step:
        name: Build
#        image: guglio/dind-buildx:latest
        image: golang
        runs-on:
          - self.hosted
          - valkyrie
        services:
          - docker
        script:
          - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game
          - cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram
          - git clone -b develop git@bitbucket.org:no-name-game/nn-grpc.git ${GOPATH}/src/bitbucket.org/no-name-game/nn-grpc
          - wget -o docker-buildx https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.darwin-amd64
          - cp docker-buildx ~/.docker/cli-plugins
          - chmod a+x ~/.docker/cli-plugins/docker-buildx
          - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; docker buildx create --use
          - docker buildx build --platform linux/arm/v8 -t valkyrie00/nn-telegram:testing -f deployment/docker/Dockerfile .

definitions:
  services:
    docker: # can only be used with a self-hosted runner
      image: docker:dind

#pipelines:
#  pull-requests:
#    "**":
#      - step:
#          script:
#            - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game
#            - cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram
#
#            # Clono SDK
#            - git clone -b develop git@bitbucket.org:no-name-game/nn-grpc.git ${GOPATH}/src/bitbucket.org/no-name-game/nn-grpc
#
#            # Linter checks
#            - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(GOPATH)/bin v1.30.0
#
#            # Build and test
#            - cd ${GOPATH}/src/bitbucket.org/no-name-game/nn-telegram
#            - golangci-lint run
#            - go build -v