image: golang

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game &&  cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/no-name

            # Manage dependencies
            - go get -u github.com/golang/dep/cmd/dep
            - cd ${GOPATH}/src/bitbucket.org/no-name-game/no-name
            - dep ensure

            # Update submodule NNSDK
            - git submodule update --init

            # Linter checks
            - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
            - golangci-lint run

            # Build and test
            - go build -v