image: golang
definitions:
  services:
    docker: # can only be used with a self-hosted runner
      image: docker:dind

pipelines:
  default:
    - step:
        name: Testing
        script:
          - echo "test"
          - echo $BITBUCKET_BRANCH
          - echo $BITBUCKET_TAG
    - step:
        # trigger: manual
        name: Deploy to Kubernetes
        image: atlassian/pipelines-kubectl
        runs-on:
          - self.hosted
          - valkyrie
        script:
          # NOTE: $KUBECONFIG is secret stored as a base64 encoded string
          # Base64 decode our kubeconfig file into a temporary kubeconfig.yml file (this will be destroyed automatically after this step runs)
#          - echo $KUBECONFIG | base64 -d > kubeconfig.yml
#          - cat kubeconfig.yml
          - sed -i s/BRANCH_NAME/3.3.5-alpha.2/g deployment/k8s/*
          - cat deployment/k8s/deployment-client.yml
          - kubectl get pods
          # Tell our Kubernetes deployment to use the new Docker image tag
          #- kubectl --kubeconfig=kubeconfig.yml --namespace=<namespace> set image deployment/<deployment-name> <deployment-name>=<docker-username>/<docker-image>:$BITBUCKET_COMMIT
  tags:
    '**':
      - step:
          name: Testing
          trigger: manual
          script:
            - echo "test"
            - echo $BITBUCKET_BRANCH
            - echo $BITBUCKET_TAG
      - step:
          name: Build And Push
          image: valkyrie00/buildx:latest
          runs-on:
            - self.hosted
            - valkyrie
          services:
            - docker
          script:
            - mkdir -p /go/src/bitbucket.org/no-name-game
            - cp -R $(pwd) /go/src/bitbucket.org/no-name-game/nn-telegram
            - git clone -b develop git@bitbucket.org:no-name-game/nn-grpc.git /go/src/bitbucket.org/no-name-game/nn-telegram/nn-grpc
            - cd /go/src/bitbucket.org/no-name-game/nn-telegram
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; docker buildx create --use
            - docker buildx build --push --platform linux/arm64 -t valkyrie00/nn-telegram:$BITBUCKET_TAG -f deployment/docker/Dockerfile .