image: golang:1.11

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - mkdir -p ${GOPATH}/src/bitbucket.org/no-name-game &&  cp -R $(pwd) ${GOPATH}/src/bitbucket.org/no-name-game/no-name

            # Manage dependencies
            - cd /go/src/bitbucket.org/no-name-game/no-name
            - curl https://glide.sh/get | sh
            - ${GOPATH}/bin/glide install

            # Linter checks
            - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.14.1
            - golangci-lint run

            # Build and test
            - go build -v
