image: golang:1.7

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - BASE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}"
          - mkdir -p ${BASE_PATH}
          - export IMPORT_PATH="${BASE_PATH}/${BITBUCKET_REPO_SLUG}"
          - ln -s ${PWD} ${IMPORT_PATH}
          - cd ${IMPORT_PATH}/no-name
          - go build -v
