image: golang
definitions:
  services:
    docker: # can only be used with a self-hosted runner
      image: docker:dind

pipelines:
  tags:
    '**':
      - step:
          name: Build And Push
          image: valkyrie00/buildx:latest
          runs-on:
            - self.hosted
            - valkyrie
          services:
            - docker
          script:
            - mkdir -p /go/src/bitbucket.org/no-name-game
            - cp -R $(pwd) /go/src/bitbucket.org/no-name-game/nn-telegram
            - git clone -b develop git@bitbucket.org:no-name-game/nn-grpc.git /go/src/bitbucket.org/no-name-game/nn-telegram/nn-grpc
            - cd /go/src/bitbucket.org/no-name-game/nn-telegram
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; docker buildx create --use
            - docker buildx build --push --platform linux/arm64 -t valkyrie00/nn-telegram:$BITBUCKET_TAG -f deployment/docker/Dockerfile .
      - step:
          name: Deploy To Production
          image: atlassian/pipelines-kubectl
#          trigger: manual
          runs-on:
            - self.hosted
            - valkyrie
          script:
            - echo $KUBECONFIG | base64 -d > kubeconfig.yml
            - sed -i s/BRANCH_NAME/$BITBUCKET_TAG/g deployment/k8s/*
            - cat deployment/k8s/deployment-client.yml
            - kubectl --kubeconfig=kubeconfig.yml apply -f deployment/k8s/deployment-client.yml
            - kubectl --kubeconfig=kubeconfig.yml apply -f deployment/k8s/deployment-notifier.yml