version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: no-name
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
      TZ: Europe/Rome
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
